blank_issues_enabled: true
contact_links:
  - name: Build Issues
    url: https://github.com/aroum/che/discussions
    about: Please ask build questions on Github Discussions
  - name: Q&A
    url: https://github.com/aroum/che/discussions
    about: Please ask questions on Github Discussionsversation with the community
